name: Setup project

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Project name'
        required: true
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        id: findandreplace2
        with:
          find: "${PROJECT_NAME}"
          replace: ${{ github.event.inputs.project_name }}
      - name: Get the final output
        run: echo "The replaced value is ${{ steps.findandreplace2.outputs.modifiedFiles }}"
      - uses: EndBug/add-and-commit@v7.0.0
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
