name: Setup project

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Project name'
        required: true
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "PROJECT_NAME"
          replace: "banana"
